- contributivity_measures.py
- fl_train_eval.py
- my_scenario.py
- simulation_run.py
Correspond to solving issue #8
> Add computation of performance scores for models trained independently

- README.md
- data_splitting.py
- scenario.py
- simulation_run.py
Just updating the README, finding better names for some variables as requested, and being more pedagogical on how to configure a custom scenario.
> A few minor tweaks before sharing

- constants.py
- contributivity.py
- fl_training.py
- scenario.py
- simulation_run.py
> 24 enrich results files

- constants.py
- contributivity.py
- contributivity_measures.py
- fl_training.py
- node.py
- scenario.py
- simulation_run.py
- utils.py
> 35 review model evaluation

- contributivity.py
- contributivity_measures.py
- simulation_run.py
The estimations of the contributivity scores should be given with their variance. If the estimation is perfect variance is zero.
> add variance in contributivity

- contributivity.py
- contributivity_measures.py
- fl_training.py
- mnist_fl_examples/mnist_baseline.py
- mnist_fl_examples/mnist_fl.py
- node.py
- scenario.py
- shapley_value/shapley.py
- simulation_run.py
- utils.py
This PR aims at gaining some readability thanks to black formater and to reorder imports. Feel free to ask for edits, I would be happy to discuss about this proposition!
> Black format

- requirements.txt
This PR to add tensorflow to the requirements!
> Add tensorflow to requirements.txt

- config.yml
- scenario.py
> epoch count in config file, default value if not

- config_quick_debug.yml
- fl_training.py
- scenario.py
> Add option for aggregation weighted per local performance

- README.md
- config.yml
- config_quick_debug.yml
- constants.py
- main.py
- utils.py
> Iss94 config file improvement

- README.md
- config_quick_debug.yml
- fl_training.py
- main.py
- partner.py
- scenario.py
- utils.py
> Advanced split of data samples among partners

- constants.py
- contributivity.py
- fl_training.py
- main.py
- scenario.py
- shapley_value/shapley.py
- utils.py
> Fix a bunch of bugs and simple issues

- fl_training.py
- main.py
- scenario.py
> Iss96 output simulation run

- main.py
This is a micro submission to add the full path of results.csv in the log.
Shall I go further?
> Log result.csv path

- main.py
- requirements.txt
- scenario.py
- utils.py
> Validate scenario before running them

- main.py
- scenario.py
- utils.py
> Add output messages with the asserts and tests of the config.yml: unkown parameters

- scenario.py
- tests.py
A couple of bug were fixed in this commit
- Fixed a bug that throws an error and canceled every run
- Removed a log output : "Computation use the full dataset" would be displayed in loop at the start of every run.
> BugFix : scenario.py

- config.yml
- config_quick_debug.yml
> Format yml config files

- README.md
- config.yml
- config_quick_debug.yml
- multi_partner_learning.py
- scenario.py
- tests.py
- utils.py
> Iss144 initialize experiment with an existing model

- config_quick_debug.yml
- constants.py
- datasets/dataset_cifar10.py
- datasets/dataset_esc50.py
- datasets/dataset_mnist.py
- datasets/dataset_titanic.py
- main.py
-create local copy of titanic when downloading it for the first time
-add try catch
-add retry, with a parameter in constants.py
> Catch fetch datasets errors

- mplc/datasets/dataset_esc50.py
- mplc/datasets/dataset_titanic.py
Signed-off-by: arthurPignet <arthur.pignet@mines-paristech.fr>
> fix bug when generating local_data folder

- mplc/partner.py
- mplc/scenario.py
Corrupt only a part of a partner's data
> Add partial corruption

- mplc/contributivity.py
- mplc/docs/documentation.md
- mplc/multi_partner_learning.py
Following the (PR 180)[https://github.com/SubstraFoundation/distributed-learning-contributivity/pull/180]
Need to be merged after the add imdb-dataset-V2
> Add the PVRL method (rebased)

- README.md
- mplc/constants.py
- mplc/contributivity.py
- mplc/docs/documentation.md
- mplc/multi_partner_learning.py
- mplc/requirements.txt
Add the LFlip method
The method is the previously denoted EM - method.
> Add LFlip method 

- mplc/partner.py
The shuffle of labels for a shuffled partner doesn't work.
> Fix the shuffling of labels

- mplc/multi_partner_learning.py
> Add epoch number in logs

- mplc/multi_partner_learning.py
> Fix early stopping

- README.md
> [demo] Let's rebase

- mplc/corruption.py
Remove transpose in corruption matrix
> Fix bug in corruption by permutation

- CONTRIBUTING.md
- config.yml
- config_quick_debug.yml
- main.py
- mplc/__init__.py
- mplc/constants.py
- mplc/contributivity.py
- mplc/corruption.py
- mplc/dataset.py
- mplc/doc/documentation.md
- mplc/experiment.py
- mplc/mpl_utils.py
- mplc/multi_partner_learning.py
- mplc/partner.py
- mplc/scenario.py
- mplc/utils.py
- notebooks/old_examples_of_results_analysis/contributivity_method_comparison.ipynb
- notebooks/old_examples_of_results_analysis/mpl.ipynb
- notebooks/tutorials/Tutorial-1_Run_your_first_scenario.ipynb
- notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
- setup.py
- tests/config_end_to_end_test_contrib.yml
- tests/end_to_end_tests.py
- tests/unit_tests.py
> Experiment object

- mplc/contributivity.py
Constraint contributivity scores for step by step methods between 0 and 1
> normalize contributivity scores in 3 SBS methods

- mplc/contributivity.py
Signed-off-by: arthurPignet <arthur.pignet@mines-paristech.fr>
> Update s-model related contributivity

- README.md
- mplc/doc/documentation.md
> Update Documentation markdown format

- mplc/doc/documentation.md
- mplc/mpl_utils.py
- mplc/multi_partner_learning.py
- mplc/partner.py
This PR follows the [PR271](https://github.com/SubstraFoundation/distributed-learning-contributivity/pull/271)
> Add gradient fusion method for multi-partner-learning

- mplc/multi_partner_learning.py
Transpose confusion matrix in theta initialisation with pretrain
> Fix smodel 

- .github/workflows/main_ci.yml
- setup.py
> Rollback to Python 3.6 & Add 3.6 to gh actions

- mplc/contributivity.py
- mplc/multi_partner_learning.py
- mplc/scenario.py
- tests/unit_tests.py
Fix aggregation method for experiments, that stayed default "data-volume"
> Homogenize aggregation and aggregation_weighting

- dev-requirements.txt
- mplc/requirements.txt
It is mandatory to use GPU on Colab
Close #327 
Signed-off-by: arthurPignet <arthur.pignet@mines-paristech.fr>
> Update to TF v2.4.1

- dev-requirements.txt
Pytest changelog: https://docs.pytest.org/en/stable/changelog.html
> Pytest 6.2.2

- README.md
- mplc/doc/documentation.md
> Clarify doc and example code snippet on running an Experiment

- .github/workflows/main_ci.yml
- CONTRIBUTING.md
- Makefile
- dev-requirements.txt
- setup.py
- tox.ini
Tox will help :
- Isolate tests, and select perimeter to launch for different contexts
- Test over multiple environnements to help integration
Main changes : 
- requirements.txt not needed anymore in the setup (are they used by another part of the application?)
- make file integration (based on #333 )
> Tox integration as test runner

- REFERENCES.md
- dev-requirements.txt
This markdown reference file contains a summary for a couple of research papers. This should help keep track of the different references related to the context of collaborative learning and Contributivity measurements.
> Papers summary
